### ISSUE TITLE
PUT /api/widget fails

### ISSUE THREAD

**Issue by maxime-allex** [Linkurious/linkurious-rest-client#125] opened 2019-12-12 15:44 UTC
Return a 400 : 

```
key: "invalid_parameter"
message: ""visualization_id" must be a number."
```

### request body : 
```
content: ...
options: ...
visualizationId: 8

**Comment by francescoinfante** [comment] 2019-12-19 15:11
Duplicate of
https://github.com/Linkurious/linkurious-server/issues/2017

**Closed by francescoinfante** 2019-12-19 15:11 UTC
Labels: type:duplicate
